/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class MyJudger */

#ifndef _Included_MyJudger
#define _Included_MyJudger
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     MyJudger
 * Method:    myexec
 * Signature: (JIJII)V
 */
  JNIEXPORT void JNICALL Java_MyJudger_myexec(JNIEnv *, jobject, jlong, jint, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
