server:
  port: 8081
  
logging:
  path: out/logs

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minos?charset=utf8mb4&useSSL=false&serverTimezone=GMT%2B8
    username: minos
    password: minos
  jpa:
    show-sql: true
    
 