server:
  port: 80
  
logging:
  path: out/logs
  level:
    org.wingsOfHope.minos.mapper: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minos?charset=utf8mb4&useSSL=false&serverTimezone=GMT%2B8
    username: minos
    password: minos
    type: com.alibaba.druid.pool.DruidDataSource
    
    mvc:
       static-path-pattern: /static/**
    
mybatis:
  typeAliasesPackage: org.wingsOfHope.minos.entity
  mapperLocations: classpath:mapper/*.xml
  